o=
[{'runtime': '', 'qd': 0, 'name': 'Sequential Preconditioning', 'threads': '', 'iops': '', 'iops_log': '', 'bw': '', 'bs': '', 'seqrand': 'Preparation', 'wmix': '', 'qdperthread': '', 'cmdline': <function DefineTests.<locals>.<lambda> at 0x7fd93d97de18>, 'desc': '', 'lat': ''},
 {'runtime': '', 'qd': 256, 'name': 'Sequential Preconditioning', 'threads': '1', 'iops': '', 'iops_log': False, 'bw': '', 'bs': '131072', 'seqrand': 'Seq Pass 1', 'wmix': '1', 'qdperthread': '256', 'cmdline': <function DefineTests.<locals>.<lambda> at 0x7fd93d97dea0>, 'desc': 'Sequential Preconditioning Pass 1', 'lat': ''},

 {'runtime': '', 'qd': 0, 'name': 'Sustained Multi-Threaded Sequential Read Tests by Block Size', 'threads': '', 'iops': '', 'iops_log': '', 'bw': '', 'bs': '', 'seqrand': 'Preparation', 'wmix': '', 'qdperthread': '', 'cmdline': <function DefineTests.<locals>.AddTestBSShmoo.<locals>.<lambda> at 0x7fd93d97df28>, 'desc': '', 'lat': ''},
 {'runtime': 1, 'qd': 256, 'name': 'Sustained Multi-Threaded Sequential Read Tests by Block Size', 'threads': 1, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 512, 'seqrand': 'Seq', 'wmix': 0, 'qdperthread': 256, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d988048>, 'desc': 'Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=512', 'lat': ''},
 {'runtime': 1, 'qd': 256, 'name': 'Sustained Multi-Threaded Sequential Read Tests by Block Size', 'threads': 1, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 1024, 'seqrand': 'Seq', 'wmix': 0, 'qdperthread': 256, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d9880d0>, 'desc': 'Sustained Multi-Threaded Sequential Read Tests by Block Size, BS=1024', 'lat': ''},

 {'runtime': '', 'qd': 0, 'name': 'Sustained Multi-Threaded Random Read Tests by Block Size', 'threads': '', 'iops': '', 'iops_log': '', 'bw': '', 'bs': '', 'seqrand': 'Preparation', 'wmix': '', 'qdperthread': '', 'cmdline': <function DefineTests.<locals>.AddTestBSShmoo.<locals>.<lambda> at 0x7fd93d988158>, 'desc': '', 'lat': ''},
 {'runtime': 1, 'qd': 256, 'name': 'Sustained Multi-Threaded Random Read Tests by Block Size', 'threads': 16, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 512, 'seqrand': 'Rand', 'wmix': 0, 'qdperthread': 16, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d9881e0>, 'desc': 'Sustained Multi-Threaded Random Read Tests by Block Size, BS=512', 'lat': ''},
 {'runtime': 1, 'qd': 256, 'name': 'Sustained Multi-Threaded Random Read Tests by Block Size', 'threads': 16, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 1024, 'seqrand': 'Rand', 'wmix': 0, 'qdperthread': 16, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d988268>, 'desc': 'Sustained Multi-Threaded Random Read Tests by Block Size, BS=1024', 'lat': ''},

 {'runtime': '', 'qd': 0, 'name': 'Sequential Write Tests with Queue Depth=1 by Block Size', 'threads': '', 'iops': '', 'iops_log': '', 'bw': '', 'bs': '', 'seqrand': 'Preparation', 'wmix': '', 'qdperthread': '', 'cmdline': <function DefineTests.<locals>.AddTestBSShmoo.<locals>.<lambda> at 0x7fd93d9882f0>, 'desc': '', 'lat': ''},
 {'runtime': 1, 'qd': 1, 'name': 'Sequential Write Tests with Queue Depth=1 by Block Size', 'threads': 1, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 512, 'seqrand': 'Seq', 'wmix': 100, 'qdperthread': 1, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d988378>, 'desc': 'Sequential Write Tests with Queue Depth=1 by Block Size, BS=512', 'lat': ''},
 {'runtime': 1, 'qd': 1, 'name': 'Sequential Write Tests with Queue Depth=1 by Block Size', 'threads': 1, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 1024, 'seqrand': 'Seq', 'wmix': 100, 'qdperthread': 1, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d988400>, 'desc': 'Sequential Write Tests with Queue Depth=1 by Block Size, BS=1024', 'lat': ''},

 {'runtime': '', 'qd': 0, 'name': 'Random Preconditioning', 'threads': '', 'iops': '', 'iops_log': '', 'bw': '', 'bs': '', 'seqrand': 'Preparation', 'wmix': '', 'qdperthread': '', 'cmdline': <function DefineTests.<locals>.<lambda> at 0x7fd93d988488>, 'desc': '', 'lat': ''},
 {'runtime': '', 'qd': 256, 'name': 'Random Preconditioning', 'threads': '1', 'iops': '', 'iops_log': False, 'bw': '', 'bs': '4096', 'seqrand': 'Rand Pass 1', 'wmix': '100', 'qdperthread': '256', 'cmdline': <function DefineTests.<locals>.<lambda> at 0x7fd93d988510>, 'desc': 'Random Preconditioning', 'lat': ''},
 {'runtime': '', 'qd': 256, 'name': 'Random Preconditioning', 'threads': '1', 'iops': '', 'iops_log': False, 'bw': '', 'bs': '4096', 'seqrand': 'Rand Pass 2', 'wmix': '100', 'qdperthread': '256', 'cmdline': <function DefineTests.<locals>.<lambda> at 0x7fd93d988598>, 'desc': 'Random Preconditioning', 'lat': ''},

 {'runtime': '', 'qd': 0, 'name': 'Sustained 4KB Random Read Tests by Number of Threads', 'threads': '', 'iops': '', 'iops_log': '', 'bw': '', 'bs': '', 'seqrand': 'Preparation', 'wmix': '', 'qdperthread': '', 'cmdline': <function DefineTests.<locals>.AddTestThreadsShmoo.<locals>.<lambda> at 0x7fd93d988620>, 'desc': '', 'lat': ''},
 {'runtime': 1, 'qd': 1, 'name': 'Sustained 4KB Random Read Tests by Number of Threads', 'threads': 1, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 4096, 'seqrand': 'Rand', 'wmix': 0, 'qdperthread': 1, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d9886a8>, 'desc': 'Sustained 4KB Random Read Tests by Number of Threads, Threads=1', 'lat': ''},
 {'runtime': 1, 'qd': 2, 'name': 'Sustained 4KB Random Read Tests by Number of Threads', 'threads': 2, 'iops': '', 'iops_log': False, 'bw': '', 'bs': 4096, 'seqrand': 'Rand', 'wmix': 0, 'qdperthread': 1, 'cmdline': <function DefineTests.<locals>.DoAddTest.<locals>.<lambda> at 0x7fd93d988730>, 'desc': 'Sustained 4KB Random Read Tests by Number of Threads, Threads=2', 'lat': ''}]
